api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    mapping:
        paths:
            - '%kernel.project_dir%/src/Security/Entity'
            - '%kernel.project_dir%/src/Security/ApiResource'
            - '%kernel.project_dir%/src/CoreConfiguration/Entity'
            - '%kernel.project_dir%/src/CoreConfiguration/Resource'

parameters:
    domain_resource_mapping:
