framework:
    messenger:
        default_bus: 'command.bus'
        buses:
            command.bus:
                middleware:
                    - App\Shared\Infrastructure\Symfony\Messenger\Middleware\LockableCommandMiddleware
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - doctrine_transaction
                    - validation
            query.bus:
                middleware:
                    - validation
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - validation
            message.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - validation
