/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import { CustomHttpClient } from '../orval/mutator/CustomHttpClient'
import type { BodyType } from '../orval/mutator/CustomHttpClient'

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
  T,
>() => T extends Y ? 1 : 2
  ? A
  : B

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >;
}[keyof T]

type UnionToIntersection<U>
  = (U extends any ? (k: U) => void : never) extends ((k: infer I) => void) ? I : never
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never

type Writable<T> = Pick<T, WritableKeys<T>>
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>

export type AdminCreationRequestUserJsonldUserReadContextOneOfHydra = typeof AdminCreationRequestUserJsonldUserReadContextOneOfHydra[keyof typeof AdminCreationRequestUserJsonldUserReadContextOneOfHydra]

export const AdminCreationRequestUserJsonldUserReadContextOneOfHydra = {
  'http://wwww3org/ns/hydra/core#': 'http://www.w3.org/ns/hydra/core#',
} as const

export type AdminCreationRequestUserJsonldUserReadContextOneOf = {
  '@vocab': string
  'hydra': AdminCreationRequestUserJsonldUserReadContextOneOfHydra
  [key: string]: unknown
}

export type AdminCreationRequestUserJsonldUserReadContext = string | AdminCreationRequestUserJsonldUserReadContextOneOf

export interface AdminCreationRequestUserJsonldUserRead {
  readonly '@context'?: AdminCreationRequestUserJsonldUserReadContext
  readonly '@id'?: string
  readonly '@type'?: string
}

export type AdminCreationRequestJsonldAdminCreateWriteEmail = string | null

export interface AdminCreationRequestJsonldAdminCreateWrite {
  email?: AdminCreationRequestJsonldAdminCreateWriteEmail
}

export type CommandInterfaceJsonldContextOneOfHydra = typeof CommandInterfaceJsonldContextOneOfHydra[keyof typeof CommandInterfaceJsonldContextOneOfHydra]

export const CommandInterfaceJsonldContextOneOfHydra = {
  'http://wwww3org/ns/hydra/core#': 'http://www.w3.org/ns/hydra/core#',
} as const

export type CommandInterfaceJsonldContextOneOf = {
  '@vocab': string
  'hydra': CommandInterfaceJsonldContextOneOfHydra
  [key: string]: unknown
}

export type CommandInterfaceJsonldContext = string | CommandInterfaceJsonldContextOneOf

export interface CommandInterfaceJsonld {
  readonly '@context'?: CommandInterfaceJsonldContext
  readonly '@id'?: string
  readonly '@type'?: string
}

export type ConstraintViolationJsonViolationsItem = {
  /** The property path of the violation */
  propertyPath?: string
  /** The message associated with the violation */
  message?: string
}

export type ConstraintViolationJsonTitle = string | null

export type ConstraintViolationJsonInstance = string | null

/**
 * Unprocessable entity
 */
export interface ConstraintViolationJson {
  status?: number
  violations?: ConstraintViolationJsonViolationsItem[]
  readonly detail?: string
  readonly type?: string
  readonly title?: ConstraintViolationJsonTitle
  readonly instance?: ConstraintViolationJsonInstance
}

export type ConstraintViolationJsonldJsonldContextOneOfHydra = typeof ConstraintViolationJsonldJsonldContextOneOfHydra[keyof typeof ConstraintViolationJsonldJsonldContextOneOfHydra]

export const ConstraintViolationJsonldJsonldContextOneOfHydra = {
  'http://wwww3org/ns/hydra/core#': 'http://www.w3.org/ns/hydra/core#',
} as const

export type ConstraintViolationJsonldJsonldContextOneOf = {
  '@vocab': string
  'hydra': ConstraintViolationJsonldJsonldContextOneOfHydra
  [key: string]: unknown
}

export type ConstraintViolationJsonldJsonldContext = string | ConstraintViolationJsonldJsonldContextOneOf

export type ConstraintViolationJsonldJsonldViolationsItem = {
  /** The property path of the violation */
  propertyPath?: string
  /** The message associated with the violation */
  message?: string
}

export type ConstraintViolationJsonldJsonldTitle = string | null

export type ConstraintViolationJsonldJsonldInstance = string | null

/**
 * Unprocessable entity
 */
export interface ConstraintViolationJsonldJsonld {
  readonly '@context'?: ConstraintViolationJsonldJsonldContext
  readonly '@id'?: string
  readonly '@type'?: string
  'status'?: number
  'violations'?: ConstraintViolationJsonldJsonldViolationsItem[]
  readonly 'detail'?: string
  readonly 'description'?: string
  readonly 'type'?: string
  readonly 'title'?: ConstraintViolationJsonldJsonldTitle
  readonly 'instance'?: ConstraintViolationJsonldJsonldInstance
}

/**
 * A short, human-readable summary of the problem.
 */
export type ErrorTitle = string | null

/**
 * A human-readable explanation specific to this occurrence of the problem.
 */
export type ErrorDetail = string | null

/**
 * A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
 */
export type ErrorInstance = string | null

/**
 * A representation of common errors.
 */
export interface Error {
  /** A short, human-readable summary of the problem. */
  readonly title?: ErrorTitle
  /** A human-readable explanation specific to this occurrence of the problem. */
  readonly detail?: ErrorDetail
  status?: number
  /** A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
  readonly instance?: ErrorInstance
  /** A URI reference that identifies the problem type */
  readonly type?: string
}

export type ErrorJsonldContextOneOfHydra = typeof ErrorJsonldContextOneOfHydra[keyof typeof ErrorJsonldContextOneOfHydra]

export const ErrorJsonldContextOneOfHydra = {
  'http://wwww3org/ns/hydra/core#': 'http://www.w3.org/ns/hydra/core#',
} as const

export type ErrorJsonldContextOneOf = {
  '@vocab': string
  'hydra': ErrorJsonldContextOneOfHydra
  [key: string]: unknown
}

export type ErrorJsonldContext = string | ErrorJsonldContextOneOf

/**
 * A short, human-readable summary of the problem.
 */
export type ErrorJsonldTitle = string | null

/**
 * A human-readable explanation specific to this occurrence of the problem.
 */
export type ErrorJsonldDetail = string | null

/**
 * A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
 */
export type ErrorJsonldInstance = string | null

export type ErrorJsonldDescription = string | null

/**
 * A representation of common errors.
 */
export interface ErrorJsonld {
  readonly '@context'?: ErrorJsonldContext
  readonly '@id'?: string
  readonly '@type'?: string
  /** A short, human-readable summary of the problem. */
  readonly 'title'?: ErrorJsonldTitle
  /** A human-readable explanation specific to this occurrence of the problem. */
  readonly 'detail'?: ErrorJsonldDetail
  'status'?: number
  /** A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
  readonly 'instance'?: ErrorJsonldInstance
  /** A URI reference that identifies the problem type */
  readonly 'type'?: string
  readonly 'description'?: ErrorJsonldDescription
}

export type ExceptionTranslationJsonldDeleteCommand = CommandInterfaceJsonld | null

export interface ExceptionTranslationJsonld {
  readonly '@id'?: string
  readonly '@type'?: string
  'key'?: string
  'domain'?: string
  'message'?: string
  readonly 'deleteCommand'?: ExceptionTranslationJsonldDeleteCommand
}

export type FaqEntryJsonldContextOneOfHydra = typeof FaqEntryJsonldContextOneOfHydra[keyof typeof FaqEntryJsonldContextOneOfHydra]

export const FaqEntryJsonldContextOneOfHydra = {
  'http://wwww3org/ns/hydra/core#': 'http://www.w3.org/ns/hydra/core#',
} as const

export type FaqEntryJsonldContextOneOf = {
  '@vocab': string
  'hydra': FaqEntryJsonldContextOneOfHydra
  [key: string]: unknown
}

export type FaqEntryJsonldContext = string | FaqEntryJsonldContextOneOf

export interface FaqEntryJsonld {
  readonly '@context'?: FaqEntryJsonldContext
  readonly '@id'?: string
  readonly '@type'?: string
  'id'?: number
  'question'?: string
  'answer'?: string
}

export interface Locale {
  id?: number
  code?: string
  name?: string
  autoTranslate?: boolean
}

export type LocaleJsonldContextOneOfHydra = typeof LocaleJsonldContextOneOfHydra[keyof typeof LocaleJsonldContextOneOfHydra]

export const LocaleJsonldContextOneOfHydra = {
  'http://wwww3org/ns/hydra/core#': 'http://www.w3.org/ns/hydra/core#',
} as const

export type LocaleJsonldContextOneOf = {
  '@vocab': string
  'hydra': LocaleJsonldContextOneOfHydra
  [key: string]: unknown
}

export type LocaleJsonldContext = string | LocaleJsonldContextOneOf

export interface LocaleJsonld {
  readonly '@context'?: LocaleJsonldContext
  readonly '@id'?: string
  readonly '@type'?: string
  'id'?: number
  'code'?: string
  'name'?: string
  'autoTranslate'?: boolean
}

export type MiscConfigurationWriteMiscConfigurationDescription = string | null

export interface MiscConfigurationWriteMiscConfiguration {
  key: string
  value: string
  description?: MiscConfigurationWriteMiscConfigurationDescription
}

export type MiscConfigurationJsonldReadMiscConfigurationContextOneOfHydra = typeof MiscConfigurationJsonldReadMiscConfigurationContextOneOfHydra[keyof typeof MiscConfigurationJsonldReadMiscConfigurationContextOneOfHydra]

export const MiscConfigurationJsonldReadMiscConfigurationContextOneOfHydra = {
  'http://wwww3org/ns/hydra/core#': 'http://www.w3.org/ns/hydra/core#',
} as const

export type MiscConfigurationJsonldReadMiscConfigurationContextOneOf = {
  '@vocab': string
  'hydra': MiscConfigurationJsonldReadMiscConfigurationContextOneOfHydra
  [key: string]: unknown
}

export type MiscConfigurationJsonldReadMiscConfigurationContext = string | MiscConfigurationJsonldReadMiscConfigurationContextOneOf

export type MiscConfigurationJsonldReadMiscConfigurationDescription = string | null

export interface MiscConfigurationJsonldReadMiscConfiguration {
  readonly '@context'?: MiscConfigurationJsonldReadMiscConfigurationContext
  readonly '@id'?: string
  readonly '@type'?: string
  'id'?: number
  'key': string
  'value': string
  'description'?: MiscConfigurationJsonldReadMiscConfigurationDescription
}

export type MiscConfigurationJsonldWriteMiscConfigurationDescription = string | null

export interface MiscConfigurationJsonldWriteMiscConfiguration {
  key: string
  value: string
  description?: MiscConfigurationJsonldWriteMiscConfigurationDescription
}

export type PasswordResetRequestResetPasswordWritePassword = string | null

export interface PasswordResetRequestResetPasswordWrite {
  password?: PasswordResetRequestResetPasswordWritePassword
}

export type PasswordResetRequestJsonldPasswordResetRequestsWriteEmail = string | null

export interface PasswordResetRequestJsonldPasswordResetRequestsWrite {
  email?: PasswordResetRequestJsonldPasswordResetRequestsWriteEmail
}

export type StaticContentJsonldContextOneOfHydra = typeof StaticContentJsonldContextOneOfHydra[keyof typeof StaticContentJsonldContextOneOfHydra]

export const StaticContentJsonldContextOneOfHydra = {
  'http://wwww3org/ns/hydra/core#': 'http://www.w3.org/ns/hydra/core#',
} as const

export type StaticContentJsonldContextOneOf = {
  '@vocab': string
  'hydra': StaticContentJsonldContextOneOfHydra
  [key: string]: unknown
}

export type StaticContentJsonldContext = string | StaticContentJsonldContextOneOf

export type StaticContentJsonldTitle = string | null

export type StaticContentJsonldContent = string | null

export interface StaticContentJsonld {
  readonly '@context'?: StaticContentJsonldContext
  readonly '@id'?: string
  readonly '@type'?: string
  'id'?: number
  'code'?: string
  'title'?: StaticContentJsonldTitle
  'content'?: StaticContentJsonldContent
}

export interface UserResetPasswordWrite {
  password?: string
}

export type UserJsonldContextOneOfHydra = typeof UserJsonldContextOneOfHydra[keyof typeof UserJsonldContextOneOfHydra]

export const UserJsonldContextOneOfHydra = {
  'http://wwww3org/ns/hydra/core#': 'http://www.w3.org/ns/hydra/core#',
} as const

export type UserJsonldContextOneOf = {
  '@vocab': string
  'hydra': UserJsonldContextOneOfHydra
  [key: string]: unknown
}

export type UserJsonldContext = string | UserJsonldContextOneOf

export type UserJsonldResetAt = string | null

export type UserJsonldResetRequestedAt = string | null

export interface UserJsonld {
  readonly '@id'?: string
  readonly '@type'?: string
  readonly '@context'?: UserJsonldContext
  'id'?: number
  'username'?: string
  /** The user roles */
  'roles'?: string[]
  'password'?: string
  'email'?: string
  'resetAt'?: UserJsonldResetAt
  'resetRequestedAt'?: UserJsonldResetRequestedAt
  /** A visual identifier that represents this user. */
  readonly 'userIdentifier'?: string
  readonly 'admin'?: boolean
}

export type ApiLocaleexceptionTranslationsGetCollectionParams = {
/**
 * The collection page number
 */
  page?: number
}

export type ApiLocaleexceptionTranslationsGetCollection200View = {
  '@id'?: string
  '@type'?: string
  'first'?: string
  'last'?: string
  'previous'?: string
  'next'?: string
}

export type ApiLocaleexceptionTranslationsGetCollection200SearchMappingItemProperty = string | null

export type ApiLocaleexceptionTranslationsGetCollection200SearchMappingItem = {
  '@type'?: string
  'variable'?: string
  'property'?: ApiLocaleexceptionTranslationsGetCollection200SearchMappingItemProperty
  'required'?: boolean
}

export type ApiLocaleexceptionTranslationsGetCollection200Search = {
  '@type'?: string
  'template'?: string
  'variableRepresentation'?: string
  'mapping'?: ApiLocaleexceptionTranslationsGetCollection200SearchMappingItem[]
}

export type ApiLocaleexceptionTranslationsGetCollection200 = {
  member: ExceptionTranslationJsonld[]
  /** @minimum 0 */
  totalItems?: number
  view?: ApiLocaleexceptionTranslationsGetCollection200View
  search?: ApiLocaleexceptionTranslationsGetCollection200Search
}

export type ApiLocalefaqEntriesGetCollectionParams = {
/**
 * The collection page number
 */
  page?: number
}

export type ApiLocalefaqEntriesGetCollection200View = {
  '@id'?: string
  '@type'?: string
  'first'?: string
  'last'?: string
  'previous'?: string
  'next'?: string
}

export type ApiLocalefaqEntriesGetCollection200SearchMappingItemProperty = string | null

export type ApiLocalefaqEntriesGetCollection200SearchMappingItem = {
  '@type'?: string
  'variable'?: string
  'property'?: ApiLocalefaqEntriesGetCollection200SearchMappingItemProperty
  'required'?: boolean
}

export type ApiLocalefaqEntriesGetCollection200Search = {
  '@type'?: string
  'template'?: string
  'variableRepresentation'?: string
  'mapping'?: ApiLocalefaqEntriesGetCollection200SearchMappingItem[]
}

export type ApiLocalefaqEntriesGetCollection200 = {
  member: FaqEntryJsonld[]
  /** @minimum 0 */
  totalItems?: number
  view?: ApiLocalefaqEntriesGetCollection200View
  search?: ApiLocalefaqEntriesGetCollection200Search
}

export type ApiLocalesGetCollectionParams = {
/**
 * The collection page number
 */
  page?: number
}

export type ApiLocalesGetCollection200View = {
  '@id'?: string
  '@type'?: string
  'first'?: string
  'last'?: string
  'previous'?: string
  'next'?: string
}

export type ApiLocalesGetCollection200SearchMappingItemProperty = string | null

export type ApiLocalesGetCollection200SearchMappingItem = {
  '@type'?: string
  'variable'?: string
  'property'?: ApiLocalesGetCollection200SearchMappingItemProperty
  'required'?: boolean
}

export type ApiLocalesGetCollection200Search = {
  '@type'?: string
  'template'?: string
  'variableRepresentation'?: string
  'mapping'?: ApiLocalesGetCollection200SearchMappingItem[]
}

export type ApiLocalesGetCollection200 = {
  member: LocaleJsonld[]
  /** @minimum 0 */
  totalItems?: number
  view?: ApiLocalesGetCollection200View
  search?: ApiLocalesGetCollection200Search
}

export type LoginCheckPostBody = {
  /** */
  email: string
  /** */
  password: string
}

export type LoginCheckPost200 = {
  /** */
  readonly token: string
}

export type ApiMiscConfigurationsGetCollectionParams = {
/**
 * The collection page number
 */
  page?: number
}

export type ApiMiscConfigurationsGetCollection200View = {
  '@id'?: string
  '@type'?: string
  'first'?: string
  'last'?: string
  'previous'?: string
  'next'?: string
}

export type ApiMiscConfigurationsGetCollection200SearchMappingItemProperty = string | null

export type ApiMiscConfigurationsGetCollection200SearchMappingItem = {
  '@type'?: string
  'variable'?: string
  'property'?: ApiMiscConfigurationsGetCollection200SearchMappingItemProperty
  'required'?: boolean
}

export type ApiMiscConfigurationsGetCollection200Search = {
  '@type'?: string
  'template'?: string
  'variableRepresentation'?: string
  'mapping'?: ApiMiscConfigurationsGetCollection200SearchMappingItem[]
}

export type ApiMiscConfigurationsGetCollection200 = {
  member: MiscConfigurationJsonldReadMiscConfiguration[]
  /** @minimum 0 */
  totalItems?: number
  view?: ApiMiscConfigurationsGetCollection200View
  search?: ApiMiscConfigurationsGetCollection200Search
}

export type ApiLocalestaticContentsGetCollectionParams = {
/**
 * The collection page number
 */
  page?: number
}

export type ApiLocalestaticContentsGetCollection200View = {
  '@id'?: string
  '@type'?: string
  'first'?: string
  'last'?: string
  'previous'?: string
  'next'?: string
}

export type ApiLocalestaticContentsGetCollection200SearchMappingItemProperty = string | null

export type ApiLocalestaticContentsGetCollection200SearchMappingItem = {
  '@type'?: string
  'variable'?: string
  'property'?: ApiLocalestaticContentsGetCollection200SearchMappingItemProperty
  'required'?: boolean
}

export type ApiLocalestaticContentsGetCollection200Search = {
  '@type'?: string
  'template'?: string
  'variableRepresentation'?: string
  'mapping'?: ApiLocalestaticContentsGetCollection200SearchMappingItem[]
}

export type ApiLocalestaticContentsGetCollection200 = {
  member: StaticContentJsonld[]
  /** @minimum 0 */
  totalItems?: number
  view?: ApiLocalestaticContentsGetCollection200View
  search?: ApiLocalestaticContentsGetCollection200Search
}

export type ApiUsersGetCollectionParams = {
/**
 * The collection page number
 */
  page?: number
}

export type ApiUsersGetCollection200View = {
  '@id'?: string
  '@type'?: string
  'first'?: string
  'last'?: string
  'previous'?: string
  'next'?: string
}

export type ApiUsersGetCollection200SearchMappingItemProperty = string | null

export type ApiUsersGetCollection200SearchMappingItem = {
  '@type'?: string
  'variable'?: string
  'property'?: ApiUsersGetCollection200SearchMappingItemProperty
  'required'?: boolean
}

export type ApiUsersGetCollection200Search = {
  '@type'?: string
  'template'?: string
  'variableRepresentation'?: string
  'mapping'?: ApiUsersGetCollection200SearchMappingItem[]
}

export type ApiUsersGetCollection200 = {
  member: UserJsonld[]
  /** @minimum 0 */
  totalItems?: number
  view?: ApiUsersGetCollection200View
  search?: ApiUsersGetCollection200Search
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Creates a AdminCreationRequest resource.
 * @summary Creates a AdminCreationRequest resource.
 */
export const apiUsersadminPost = (
  adminCreationRequestJsonldAdminCreateWrite: BodyType<AdminCreationRequestJsonldAdminCreateWrite>,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<AdminCreationRequestUserJsonldUserRead>(
    { url: `/users/admin`, method: 'POST',
      headers: { 'Content-Type': 'application/ld+json' },
      data: adminCreationRequestJsonldAdminCreateWrite,
    },
    options)
}

/**
 * Retrieves the collection of ExceptionTranslation resources.
 * @summary Retrieves the collection of ExceptionTranslation resources.
 */
export const apiLocaleexceptionTranslationsGetCollection = (
  locale: string,
  params?: ApiLocaleexceptionTranslationsGetCollectionParams,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<ApiLocaleexceptionTranslationsGetCollection200>(
    { url: `/${locale}/exception_translations`, method: 'GET',
      params,
    },
    options)
}

/**
 * Retrieves the collection of FaqEntry resources.
 * @summary Retrieves the collection of FaqEntry resources.
 */
export const apiLocalefaqEntriesGetCollection = (
  locale: string,
  params?: ApiLocalefaqEntriesGetCollectionParams,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<ApiLocalefaqEntriesGetCollection200>(
    { url: `/${locale}/faq_entries`, method: 'GET',
      params,
    },
    options)
}

/**
 * Creates a FaqEntry resource.
 * @summary Creates a FaqEntry resource.
 */
export const apiLocalefaqEntriesPost = (
  locale: string,
  faqEntryJsonld: BodyType<NonReadonly<FaqEntryJsonld>>,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<FaqEntryJsonld>(
    { url: `/${locale}/faq_entries`, method: 'POST',
      headers: { 'Content-Type': 'application/ld+json' },
      data: faqEntryJsonld,
    },
    options)
}

/**
 * Retrieves a FaqEntry resource.
 * @summary Retrieves a FaqEntry resource.
 */
export const apiLocalefaqEntriesIdGet = (
  locale: string,
  id: string,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<FaqEntryJsonld>(
    { url: `/${locale}/faq_entries/${id}`, method: 'GET',
    },
    options)
}

/**
 * Replaces the FaqEntry resource.
 * @summary Replaces the FaqEntry resource.
 */
export const apiLocalefaqEntriesIdPut = (
  locale: string,
  id: string,
  faqEntryJsonld: BodyType<NonReadonly<FaqEntryJsonld>>,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<FaqEntryJsonld>(
    { url: `/${locale}/faq_entries/${id}`, method: 'PUT',
      headers: { 'Content-Type': 'application/ld+json' },
      data: faqEntryJsonld,
    },
    options)
}

/**
 * Removes the FaqEntry resource.
 * @summary Removes the FaqEntry resource.
 */
export const apiLocalefaqEntriesIdDelete = (
  locale: string,
  id: string,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<null>(
    { url: `/${locale}/faq_entries/${id}`, method: 'DELETE',
    },
    options)
}

/**
 * Retrieves the collection of Locale resources.
 * @summary Retrieves the collection of Locale resources.
 */
export const apiLocalesGetCollection = (
  params?: ApiLocalesGetCollectionParams,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<ApiLocalesGetCollection200>(
    { url: `/locales`, method: 'GET',
      params,
    },
    options)
}

/**
 * Creates a Locale resource.
 * @summary Creates a Locale resource.
 */
export const apiLocalesPost = (
  localeJsonld: BodyType<NonReadonly<LocaleJsonld>>,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<LocaleJsonld>(
    { url: `/locales`, method: 'POST',
      headers: { 'Content-Type': 'application/ld+json' },
      data: localeJsonld,
    },
    options)
}

/**
 * Removes the Locale resource.
 * @summary Removes the Locale resource.
 */
export const apiLocalesIdDelete = (
  id: string,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<null>(
    { url: `/locales/${id}`, method: 'DELETE',
    },
    options)
}

/**
 * Updates the Locale resource.
 * @summary Updates the Locale resource.
 */
export const apiLocalesIdPatch = (
  id: string,
  locale: BodyType<Locale>,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<LocaleJsonld>(
    { url: `/locales/${id}`, method: 'PATCH',
      headers: { 'Content-Type': 'application/merge-patch+json' },
      data: locale,
    },
    options)
}

/**
 * Creates a user token.
 * @summary Creates a user token.
 */
export const loginCheckPost = (
  loginCheckPostBody: BodyType<LoginCheckPostBody>,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<LoginCheckPost200>(
    { url: `/auth`, method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: loginCheckPostBody,
    },
    options)
}

/**
 * Retrieves the collection of MiscConfiguration resources.
 * @summary Retrieves the collection of MiscConfiguration resources.
 */
export const apiMiscConfigurationsGetCollection = (
  params?: ApiMiscConfigurationsGetCollectionParams,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<ApiMiscConfigurationsGetCollection200>(
    { url: `/misc_configurations`, method: 'GET',
      params,
    },
    options)
}

/**
 * Creates a MiscConfiguration resource.
 * @summary Creates a MiscConfiguration resource.
 */
export const apiMiscConfigurationsPost = (
  miscConfigurationJsonldWriteMiscConfiguration: BodyType<MiscConfigurationJsonldWriteMiscConfiguration>,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<MiscConfigurationJsonldReadMiscConfiguration>(
    { url: `/misc_configurations`, method: 'POST',
      headers: { 'Content-Type': 'application/ld+json' },
      data: miscConfigurationJsonldWriteMiscConfiguration,
    },
    options)
}

/**
 * Retrieves a MiscConfiguration resource.
 * @summary Retrieves a MiscConfiguration resource.
 */
export const apiMiscConfigurationsIdGet = (
  id: string,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<MiscConfigurationJsonldReadMiscConfiguration>(
    { url: `/misc_configurations/${id}`, method: 'GET',
    },
    options)
}

/**
 * Removes the MiscConfiguration resource.
 * @summary Removes the MiscConfiguration resource.
 */
export const apiMiscConfigurationsIdDelete = (
  id: string,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<null>(
    { url: `/misc_configurations/${id}`, method: 'DELETE',
    },
    options)
}

/**
 * Updates the MiscConfiguration resource.
 * @summary Updates the MiscConfiguration resource.
 */
export const apiMiscConfigurationsIdPatch = (
  id: string,
  miscConfigurationWriteMiscConfiguration: BodyType<MiscConfigurationWriteMiscConfiguration>,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<MiscConfigurationJsonldReadMiscConfiguration>(
    { url: `/misc_configurations/${id}`, method: 'PATCH',
      headers: { 'Content-Type': 'application/merge-patch+json' },
      data: miscConfigurationWriteMiscConfiguration,
    },
    options)
}

/**
 * Creates a PasswordResetRequest resource.
 * @summary Creates a PasswordResetRequest resource.
 */
export const apiUserspasswordResetRequestssendPost = (
  passwordResetRequestJsonldPasswordResetRequestsWrite: BodyType<PasswordResetRequestJsonldPasswordResetRequestsWrite>,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<unknown>(
    { url: `/users/password-reset-requests/send`, method: 'POST',
      headers: { 'Content-Type': 'application/ld+json' },
      data: passwordResetRequestJsonldPasswordResetRequestsWrite,
    },
    options)
}

/**
 * Updates the PasswordResetRequest resource.
 * @summary Updates the PasswordResetRequest resource.
 */
export const apiUserspasswordResetRequestsTokenapplyPatch = (
  token: string,
  passwordResetRequestResetPasswordWrite: BodyType<PasswordResetRequestResetPasswordWrite>,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<unknown>(
    { url: `/users/password-reset-requests/${token}/apply`, method: 'PATCH',
      headers: { 'Content-Type': 'application/merge-patch+json' },
      data: passwordResetRequestResetPasswordWrite,
    },
    options)
}

/**
 * Retrieves the collection of StaticContent resources.
 * @summary Retrieves the collection of StaticContent resources.
 */
export const apiLocalestaticContentsGetCollection = (
  locale: string,
  params?: ApiLocalestaticContentsGetCollectionParams,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<ApiLocalestaticContentsGetCollection200>(
    { url: `/${locale}/static_contents`, method: 'GET',
      params,
    },
    options)
}

/**
 * Creates a StaticContent resource.
 * @summary Creates a StaticContent resource.
 */
export const apiLocalestaticContentsPost = (
  locale: string,
  staticContentJsonld: BodyType<NonReadonly<StaticContentJsonld>>,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<StaticContentJsonld>(
    { url: `/${locale}/static_contents`, method: 'POST',
      headers: { 'Content-Type': 'application/ld+json' },
      data: staticContentJsonld,
    },
    options)
}

/**
 * Retrieves a StaticContent resource.
 * @summary Retrieves a StaticContent resource.
 */
export const apiLocalestaticContentsIdGet = (
  locale: string,
  id: string,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<StaticContentJsonld>(
    { url: `/${locale}/static_contents/${id}`, method: 'GET',
    },
    options)
}

/**
 * Replaces the StaticContent resource.
 * @summary Replaces the StaticContent resource.
 */
export const apiLocalestaticContentsIdPut = (
  locale: string,
  id: string,
  staticContentJsonld: BodyType<NonReadonly<StaticContentJsonld>>,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<StaticContentJsonld>(
    { url: `/${locale}/static_contents/${id}`, method: 'PUT',
      headers: { 'Content-Type': 'application/ld+json' },
      data: staticContentJsonld,
    },
    options)
}

/**
 * Removes the StaticContent resource.
 * @summary Removes the StaticContent resource.
 */
export const apiLocalestaticContentsIdDelete = (
  locale: string,
  id: string,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<null>(
    { url: `/${locale}/static_contents/${id}`, method: 'DELETE',
    },
    options)
}

/**
 * Retrieves the collection of User resources.
 * @summary Retrieves the collection of User resources.
 */
export const apiUsersGetCollection = (
  params?: ApiUsersGetCollectionParams,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<ApiUsersGetCollection200>(
    { url: `/users`, method: 'GET',
      params,
    },
    options)
}

/**
 * Retrieves a User resource.
 * @summary Retrieves a User resource.
 */
export const apiUsersmeGet = (

  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<UserJsonld>(
    { url: `/users/me`, method: 'GET',
    },
    options)
}

/**
 * Removes the User resource.
 * @summary Removes the User resource.
 */
export const apiUsersIdDelete = (
  id: string,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<null>(
    { url: `/users/${id}`, method: 'DELETE',
    },
    options)
}

/**
 * Updates the User resource.
 * @summary Updates the User resource.
 */
export const apiUsersIdupdatePasswordPatch = (
  id: string,
  userResetPasswordWrite: BodyType<UserResetPasswordWrite>,
  options?: SecondParameter<typeof CustomHttpClient>) => {
  return CustomHttpClient<UserJsonld>(
    { url: `/users/${id}/update_password`, method: 'PATCH',
      headers: { 'Content-Type': 'application/merge-patch+json' },
      data: userResetPasswordWrite,
    },
    options)
}

export type ApiUsersadminPostResult = NonNullable<Awaited<ReturnType<typeof apiUsersadminPost>>>
export type ApiLocaleexceptionTranslationsGetCollectionResult = NonNullable<Awaited<ReturnType<typeof apiLocaleexceptionTranslationsGetCollection>>>
export type ApiLocalefaqEntriesGetCollectionResult = NonNullable<Awaited<ReturnType<typeof apiLocalefaqEntriesGetCollection>>>
export type ApiLocalefaqEntriesPostResult = NonNullable<Awaited<ReturnType<typeof apiLocalefaqEntriesPost>>>
export type ApiLocalefaqEntriesIdGetResult = NonNullable<Awaited<ReturnType<typeof apiLocalefaqEntriesIdGet>>>
export type ApiLocalefaqEntriesIdPutResult = NonNullable<Awaited<ReturnType<typeof apiLocalefaqEntriesIdPut>>>
export type ApiLocalefaqEntriesIdDeleteResult = NonNullable<Awaited<ReturnType<typeof apiLocalefaqEntriesIdDelete>>>
export type ApiLocalesGetCollectionResult = NonNullable<Awaited<ReturnType<typeof apiLocalesGetCollection>>>
export type ApiLocalesPostResult = NonNullable<Awaited<ReturnType<typeof apiLocalesPost>>>
export type ApiLocalesIdDeleteResult = NonNullable<Awaited<ReturnType<typeof apiLocalesIdDelete>>>
export type ApiLocalesIdPatchResult = NonNullable<Awaited<ReturnType<typeof apiLocalesIdPatch>>>
export type LoginCheckPostResult = NonNullable<Awaited<ReturnType<typeof loginCheckPost>>>
export type ApiMiscConfigurationsGetCollectionResult = NonNullable<Awaited<ReturnType<typeof apiMiscConfigurationsGetCollection>>>
export type ApiMiscConfigurationsPostResult = NonNullable<Awaited<ReturnType<typeof apiMiscConfigurationsPost>>>
export type ApiMiscConfigurationsIdGetResult = NonNullable<Awaited<ReturnType<typeof apiMiscConfigurationsIdGet>>>
export type ApiMiscConfigurationsIdDeleteResult = NonNullable<Awaited<ReturnType<typeof apiMiscConfigurationsIdDelete>>>
export type ApiMiscConfigurationsIdPatchResult = NonNullable<Awaited<ReturnType<typeof apiMiscConfigurationsIdPatch>>>
export type ApiUserspasswordResetRequestssendPostResult = NonNullable<Awaited<ReturnType<typeof apiUserspasswordResetRequestssendPost>>>
export type ApiUserspasswordResetRequestsTokenapplyPatchResult = NonNullable<Awaited<ReturnType<typeof apiUserspasswordResetRequestsTokenapplyPatch>>>
export type ApiLocalestaticContentsGetCollectionResult = NonNullable<Awaited<ReturnType<typeof apiLocalestaticContentsGetCollection>>>
export type ApiLocalestaticContentsPostResult = NonNullable<Awaited<ReturnType<typeof apiLocalestaticContentsPost>>>
export type ApiLocalestaticContentsIdGetResult = NonNullable<Awaited<ReturnType<typeof apiLocalestaticContentsIdGet>>>
export type ApiLocalestaticContentsIdPutResult = NonNullable<Awaited<ReturnType<typeof apiLocalestaticContentsIdPut>>>
export type ApiLocalestaticContentsIdDeleteResult = NonNullable<Awaited<ReturnType<typeof apiLocalestaticContentsIdDelete>>>
export type ApiUsersGetCollectionResult = NonNullable<Awaited<ReturnType<typeof apiUsersGetCollection>>>
export type ApiUsersmeGetResult = NonNullable<Awaited<ReturnType<typeof apiUsersmeGet>>>
export type ApiUsersIdDeleteResult = NonNullable<Awaited<ReturnType<typeof apiUsersIdDelete>>>
export type ApiUsersIdupdatePasswordPatchResult = NonNullable<Awaited<ReturnType<typeof apiUsersIdupdatePasswordPatch>>>
