module.exports = {
  client: {
    input: {
      target: '/var/shared/openai_schema.json',
      override: {
        transformer: './orval/transformer/CustomTransformer.js',
      },
    },
    output: {
      target: './services/client.ts',
      override: {
        mutator: {
          path: './orval/mutator/CustomHttpClient.ts',
          name: 'CustomHttpClient',
        },
        header: info => [
          `Generated by orval 🍺`,
          `Do not edit manually.`,
          ...(info.title ? [info.title] : []),
          ...(info.description ? [info.description] : []),
          ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
        ],
      },
    },
  },
}
